#!/bin/bash

# Get WiFi status from sysfs
# $BLOCK_INSTANCE is an option that can be set in i3block.conf
INTERFACE="${BLOCK_INSTANCE:-eth0}"

# Don't display if interface is not found.
[[ ! -d /sys/class/net/${INTERFACE} ]] && exit

# Get link status
STATUS=$(cat /sys/class/net/${INTERFACE}/operstate)

# Get internet status
ping -q -W 1 -c 1 8.8.8.8 &> /dev/null
if [[ $? -eq 0 ]]; then
    ONLINE="yes"
else
    ONLINE="no"
fi

# Set Icon
ICON=""

# Set Color
if [ $STATUS == "down" ] ; then
    COLOR="#4f5b66"
elif [ $STATUS == "up" ] ; then
    if [ $ONLINE == "yes" ] ; then
        COLOR="#a3be8c"
    else
        COLOR="#ebcb8b"
    fi
fi

echo $ICON      # Full text label
echo $ICON      # Short text label (Used when status line gets too long)
echo $COLOR     # Label color
