#!/bin/bash

# Get WiFi status from sysfs
# $BLOCK_INSTANCE is an option that can be set in i3block.conf
INTERFACE="${BLOCK_INSTANCE:-wlan0}"

# Don't display if machine has no wireless or if interface is not found.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit 

# Get status
STATUS=$(cat /sys/class/net/${INTERFACE}/operstate)

# Get link quality
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

## NOTE ##
# broadcom-wl proprietary drivers restrict access to /proc/net/wireless.
# Either give grep the CAP_NET_ADMIN capability using setcap...
# "setcap cap_net_admin+ep /usr/bin/grep"
# Or add the grep half of the query to sudoers for the user and uncomment below.
# QUALITY=$(sudo grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# Set Icon
if [ $STATUS == "down" ] ; then
    ICON=""
    COLOR="#4f5b66"
elif [ $STATUS == "up" ] ; then
    ICON=""
    if [ $QUALITY -ge 70 ] ; then
        COLOR="#a3be8c"
    elif [ $QUALITY -ge 50 ] ; then
        COLOR="#ebcb8b"
    elif [ $QUALITY -ge 30 ] ; then
        COLOR="#d08770"
    elif [ $QUALITY -lt 30 ] ; then
        COLOR="#bf616a"
    fi
fi    

echo $ICON      # Full text label
echo $ICON      # Short text label (Used when status line gets too long)
echo $COLOR     # Label color
